server:
  port: 8089
  servlet:
    context-path: /fast-platform

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fast-platform?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis-plus:
  mapper-locations: classpath*:/mapper/*/**Mapper.xml
  typeAliasesPackage: com.nwx.entity
  global-config:
    db-config:
      db-column-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com:
      nwx:
        mapper: debug

beetl:
  templatesPath: templates
beetlsql:
  enabled: false